[package]
name = "nasbench"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2018"

[dependencies]
crc = "1"
byteorder = "1"
serde_json = "1"
structopt = "0.2"
trackable = "0.2"
