[package]
name = "nasbench"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10"
bytecodec = "0.4"
byteorder = "1"
crc = "1"
protobuf_codec = "0.2"
serde_json = "1"
structopt = "0.2"
trackable = "0.2"
